POST http://localhost:3333/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3ODc2OTkzLCJleHAiOjE2OTc4Nzc4OTN9.oMFVNQG14231eK4HK7a1tcyk1jLJ9solln_rAf_TuKw

{
  "trainingId": 242,
  "count": 30
}
###



PATCH http://localhost:3333/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3ODc2OTkzLCJleHAiOjE2OTc4Nzc4OTN9.oMFVNQG14231eK4HK7a1tcyk1jLJ9solln_rAf_TuKw

{
  "trainingId": 242,
  "count": 30
}
###



GET http://localhost:3333/balance HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3ODc2OTkzLCJleHAiOjE2OTc4Nzc4OTN9.oMFVNQG14231eK4HK7a1tcyk1jLJ9solln_rAf_TuKw

###
