POST http://localhost:3333/feedback HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3OTgzMzk0LCJleHAiOjE2OTc5ODQyOTR9.GekK6XKuFAsqttKq7SoEiWEbVkpuDRZqOWrdKnS-rrQ

{
  "trainingId": 242,
  "rating": 1,
  "text": "string сто символов это много, это очень много, это невообразимо много, я не знаю кто бы мог написать столько букв"
}
###

GET http://localhost:3333/feedback/242 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3OTg0MDU4LCJleHAiOjE2OTc5ODQ5NTh9.KI2uhLCzq7oipdUaX6hOvNH00SGSsqEA8MHb84LbLjc

###

GET http://localhost:3333/feedback/242/rating HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3OTg0NTM4LCJleHAiOjE2OTc5ODU0Mzh9.4QcKBEaqY3vK29jrzf-YhxWisNekIIzczXImdoTt6f4

###
