POST http://localhost:3333/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk4MDM1MzI4LCJleHAiOjE2OTgwMzYyMjh9.AGGkujTt-Zzz3UL-dtxR_xiStopoR_osMMZqQii4LUY

{
  "coachId": "65329a910b645fb5e70f5f2d"
}
###

DELETE http://localhost:3333/subscribe/65329a910b645fb5e70f5f2d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk4MDM1MzI4LCJleHAiOjE2OTgwMzYyMjh9.AGGkujTt-Zzz3UL-dtxR_xiStopoR_osMMZqQii4LUY

###

POST http://localhost:3333/notify HTTP/1.1

###
#653518fec8a35e9d28b79013
