POST http://localhost:3333/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3OTc5NjA2LCJleHAiOjE2OTc5ODA1MDZ9.E32IuWzvSPHiyzxTS_g9Q_aQAyuEGJaUaov1P7uZHc8

{
  "coachId": "65329a910b645fb5e70f5f2d"
}
###

DELETE http://localhost:3333/subscribe/6521fe64baaf09d0704c280e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNjIxNmVmN2U4ODMzZjA3YzE1NTUiLCJlbWFpbCI6InRvcmFuc21vckBvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY5Nzk3OTY5OCwiZXhwIjoxNjk3OTgwNTk4fQ.0U5JS4sKKU1-MAto1SE_oDn5-D6C0Ak0nzVblMAX-Fg

###

POST http://localhost:3333/notify HTTP/1.1

###
#653518fec8a35e9d28b79013
