

GET http://localhost:3333/notification HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyOWE5MTBiNjQ1ZmI1ZTcwZjVmMmQiLCJlbWFpbCI6Im9tb3Z1LW9tb3Z1MEBvam95by5jb20iLCJuYW1lIjoiVG9zaGlhIiwicm9sZSI6ImNvYWNoIiwiaWF0IjoxNjk4MDM5NTY1LCJleHAiOjE2OTgwNDA0NjV9.cyB0vniY0g29KoBqPkRGzDXdn9YKWocDZoMTYUi4UTc

###

DELETE http://localhost:3333/notification/6533e8e4d12ea08cc6a216dc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3OTAxMDA2LCJleHAiOjE2OTc5MDE5MDZ9.S7zfXtepg-_1MtNdVart0Wkc35M0FxC-GRQeVlLow1M

###
