##Список

GET http://localhost:3333/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5Nzg3MTk4MiwiZXhwIjoxNjk3ODcyODgyfQ.jxRxtR5Ctq9dz0lDQi41qnfY8SpH4yJoTJBypV6qn3o

###

GET http://localhost:3333/users?sort=role&order=asc&limit=5&page=2&level=beginner&trainingType=running&location=Петроградская HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5Nzg2NjQ0NiwiZXhwIjoxNjk3ODY3MzQ2fQ.LEUd0C_XHHdNl-A832mUqeMI_0oGLaxj__EQVMW1i24

###

GET http://localhost:3333/users?sort=role&order=asc&limit=5&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5Nzg2NjQ0NiwiZXhwIjoxNjk3ODY3MzQ2fQ.LEUd0C_XHHdNl-A832mUqeMI_0oGLaxj__EQVMW1i24

###

GET http://localhost:3333/users?sort=role&order=asc&limit=5&page=1&trainingType=yoga HTTP/1.1

###

##Получить по коду

GET http://localhost:3333/users/65329a910b645fb5e70f5f2d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5Nzg3MDY3OCwiZXhwIjoxNjk3ODcxNTc4fQ.XuFKxzziHkxWjyySdR5Eht7tF-GxB9kp_D6QH5j81LY

###

##Update

PATCH http://localhost:3333/users/6533486b3102158718d74409 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5Nzg3NDkzNiwiZXhwIjoxNjk3ODc1ODM2fQ.DLEYnoagQLB8Dp17c2g4VcKYgGlMx5M-f7_rUmYuK3w

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: text/plain

{
  "name": "Bobik",
  "isReady": "true",
  "addition": {
    "trainingCalories": 3670
  }
}
