## Создать заказ

POST http://localhost:3333/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMzNDg2YjMxMDIxNTg3MThkNzQ0MDkiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iaWsiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3OTAxOTcyLCJleHAiOjE2OTc5MDI4NzJ9.YAr9hO6cUvq8_1y8PwWDUHyWaUlRb0TEebV6oOPvpI8

{
  "trainingId": 243,
  "count": 3,
  "paymentOption": "visa"
}
###

GET http://localhost:3333/order?limit=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyOWE5MTBiNjQ1ZmI1ZTcwZjVmMmQiLCJlbWFpbCI6Im9tb3Z1LW9tb3Z1MEBvam95by5jb20iLCJuYW1lIjoiVG9zaGlhIiwicm9sZSI6ImNvYWNoIiwiaWF0IjoxNjk3OTAzNzQzLCJleHAiOjE2OTc5MDQ2NDN9.yvGoInp8G_ZuytFpVpRAeYv3cPCYTf0o-26vGieGk4U

###

GET http://localhost:3333/order HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyOWE5MTBiNjQ1ZmI1ZTcwZjVmMmQiLCJlbWFpbCI6Im9tb3Z1LW9tb3Z1MEBvam95by5jb20iLCJuYW1lIjoiVG9zaGlhIiwicm9sZSI6ImNvYWNoIiwiaWF0IjoxNjk3OTEwNzYxLCJleHAiOjE2OTc5MTE2NjF9.bsqAyX5dVdSXJARQon6Fc2gl3c3dpz5vHZY6gSEvwY4
