version: '3.9'
services:
  fit-friends.bff:
    container_name: fit-friend.bff
    restart: always
    image: fit-friends.bff:latest
    env_file:
      - .fit-friends.bff.env
    ports:
      - "3333:3333"
    networks:
      - fit-friends.rabbit
      - fit-friends.bff

networks:
  fit-friends.rabbit:
    external: true
  fit-friends.bff:
    external: true
