

GET http://localhost:3111/notification HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyOTY2ZDUzODg4MDRhNjhiOTllODIiLCJlbWFpbCI6Im93bXVzdEBwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3MjA5MDMwLCJleHAiOjE2OTcyMDk5MzB9.8y76YGXzlkYqA54Jh7Y2lPMLDG5636jj28mJBg22BAg

###

DELETE http://localhost:3111/notification/6529599b2e1ab7b2dfb88fb9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyOTY2ZDUzODg4MDRhNjhiOTllODIiLCJlbWFpbCI6Im93bXVzdEBwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNjk3MjA5MDMwLCJleHAiOjE2OTcyMDk5MzB9.8y76YGXzlkYqA54Jh7Y2lPMLDG5636jj28mJBg22BAg

###
