version: '3.9'
services:
  fit-friend.uploader.mongo:
    image: mongo:4.2
    restart: always
    container_name: fit-friend.uploader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fit-friend-uploader

    ports:
      - '27018:27017'

    volumes:
      - fit-friend.mongo.uploader:/data/db

    networks:
      - fit-friend.uploader

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fit-friend-uploader --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  fit-friend.uploader.mongo.express:
    image: mongo-express
    restart: always
    container_name: fit-friend.uploader.mongo.ui
    ports:
      - '8083:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@fit-friend.uploader.mongo:27017/

    networks:
      - fit-friend.uploader
volumes:
  fit-friend.mongo.uploader:

networks:
  fit-friend.uploader:
      driver: bridge
