POST http://localhost:3444/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzA0MDAwNiwiZXhwIjoxNjk3MDQwOTA2fQ.hw5rwulkN2DpASO0j3sxLVI6RaBdzyDPCkf4Dc_jSEE

{
  "trainingId": 3,
  "count": 30
}
###

POST http://localhost:3444/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzA0MDAwNiwiZXhwIjoxNjk3MDQwOTA2fQ.hw5rwulkN2DpASO0j3sxLVI6RaBdzyDPCkf4Dc_jSEE

{
  "trainingId": 1,
  "count": 10
}
###

POST http://localhost:3444/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzA0MDAwNiwiZXhwIjoxNjk3MDQwOTA2fQ.hw5rwulkN2DpASO0j3sxLVI6RaBdzyDPCkf4Dc_jSEE

{
  "trainingId": 2,
  "count": 20
}
###


DELETE http://localhost:3444/balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzA0MDAwNiwiZXhwIjoxNjk3MDQwOTA2fQ.hw5rwulkN2DpASO0j3sxLVI6RaBdzyDPCkf4Dc_jSEE

{
  "trainingId": 3,
  "count": 1
}
###


GET http://localhost:3444/balance HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzA0MDAwNiwiZXhwIjoxNjk3MDQwOTA2fQ.hw5rwulkN2DpASO0j3sxLVI6RaBdzyDPCkf4Dc_jSEE

###
