version: '3.9'
services:
  fit-friends.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: fit-friends.notify.fakesmtp
    hostname: fakesmtp
    ports:
      - "8025:8025"
      - "1083:8080"

  fit-friends.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: fit-friends.notify.rabbitmq
    ports:
      - '1088:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  fit-friend.notify.mongo:
    image: mongo:4.2
    restart: always
    container_name: fit-friend-notify_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fit-friend-notify-mongo
    ports:
      - "27019:27017"
    volumes:
      - fit-friend-notify_data:/data/db
    networks:
      - fit-friend.notify
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fit-friend-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  fit-friend.mongodb-express:
    image: mongo-express:latest
    restart: always
    container_name: fit-friend-notify_mongo-express
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@fit-friend-notify_mongodb:27017/
    networks:
      - fit-friend.notify

volumes:
  fit-friend-notify_data:

networks:
  fit-friend.notify:
      driver: bridge
