POST http://localhost:3444/feedback HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzI2MzE0OSwiZXhwIjoxNjk3MjY0MDQ5fQ.4-gix-ZxMN_W8i-A_S4QXKAyqFMPGSnh4SoXJ741prU

{
  "trainingId": 1,
  "rating": 1,
  "text": "string сто символов это много, это очень много, это невообразимо много, ф не знаю кто бы мог написать столько букв"
}
###

GET http://localhost:3444/feedback/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzI2MjIxNCwiZXhwIjoxNjk3MjYzMTE0fQ.GdfAk-YXc280M87F5QW4klKBmJF6rrW2MqBtU-SBl7U

###

GET http://localhost:3444/feedback/1/rating HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTIyYzlmNjc4OTQ4ZWQ3M2IxNTcyMmEiLCJlbWFpbCI6InNub3dAcGlzZW0ubG9jYWwiLCJuYW1lIjoiQm9iIiwicm9sZSI6InNwb3J0c21hbiIsImlhdCI6MTY5NzI2MjIxNCwiZXhwIjoxNjk3MjYzMTE0fQ.GdfAk-YXc280M87F5QW4klKBmJF6rrW2MqBtU-SBl7U

###
